### ISSUE TITLE
Create a page (implementing the facial recognition code) which detects faces and then marks the students present or not.

### ISSUE THREAD

**Issue by Bread21234** [CSAllenISD/2023-ISP-AutomatedAttendance#50]

**Comment by VJCS185** [comment]
We should make sure that it is a live feed so the teacher will be able to notice any mistakes as the students walk in. If it is not live then the teacher would have to call out attendance to check the accuracy of the system which would make this system pointless, although if it is live the teacher can just check the system while the students walk into the class.

**Comment by AkshayVemulapalli** [comment]
I think that making the teacher monitor the accuracy of the system takes away from its purpose of saving time, although it might be fine for the minimum viable product or the early stages of the product. I think we can ensure the accuracy of the system by making it announce out loud when a student has been marked present, so that the student will know if the model made a mistake or didn't recognize them yet.

**Comment by RusticKnite** [comment]
Too similar to Issue #66 refer to this Issue for further reference and documentation on matter.
