### ISSUE TITLE
Make an application for students to see their attendance on their devices.

### ISSUE THREAD

**Issue by VJCS185** [CSAllenISD/2023-ISP-AutomatedAttendance#57]
We should make an application that works on both android, apple, and other computer operating systems in which students can see their attendance. This will allow students to see if the system made a mistake as they walked in immediately and the student can notify the teacher who can quickly resolve the issue. This would minimize time waste for students as they don't have to email their teachers of mistakes in attendance days after it happened or have to go to the attendance clerk to discuss the incorrect absence.

**Comment by AkshayVemulapalli** [comment]
This is an interesting idea. I think this is something we can implement later after we finish the main website/product for teachers. Or we can make the website announce out loud when a student is marked present, so they will know immediately if the system made a mistake. 

Maybe it will be possible to connect our databases with Skyward in the future so that students can just view their attendance there like they do currently.

**Comment by RusticKnite** [comment]
Too similar and has same reasoning as issue #58 see here for further documentation.
